// seeds/lookups.js
export async function seed(knex) {
  // Clean existing global defaults
  await knex('system.lookup_values').whereNull('tenant_id').delete().catch(() => {});
  await knex('system.lookup_definitions').delete().catch(() => {});

  const defs = [
    { lookup_type: 'stop_categories', display_name: 'Categorii opriri', display_name_en: 'Stop categories', is_system: true },
    { lookup_type: 'scrap_reasons', display_name: 'Motive rebuturi', display_name_en: 'Scrap reasons', is_system: true },
    { lookup_type: 'machine_types', display_name: 'Tipuri masini', display_name_en: 'Machine types', is_system: true },
    { lookup_type: 'tool_types', display_name: 'Tipuri scule', display_name_en: 'Tool types', is_system: true },
    { lookup_type: 'item_categories', display_name: 'Categorii inventar', display_name_en: 'Item categories', is_system: true },
    { lookup_type: 'units_of_measure', display_name: 'Unitati de masura', display_name_en: 'Units of measure', is_system: true },
    { lookup_type: 'leave_types', display_name: 'Tipuri concediu', display_name_en: 'Leave types', is_system: true },
    { lookup_type: 'intervention_types', display_name: 'Tipuri interventie', display_name_en: 'Intervention types', is_system: true },
    { lookup_type: 'priority_levels', display_name: 'Nivele prioritate', display_name_en: 'Priority levels', is_system: true },
    { lookup_type: 'company_types', display_name: 'Tipuri companie', display_name_en: 'Company types', is_system: true },
    { lookup_type: 'operation_types', display_name: 'Tipuri operatii BOM', display_name_en: 'BOM operation types', is_system: true },
    { lookup_type: 'order_statuses', display_name: 'Statusuri comenzi', display_name_en: 'Order statuses', is_system: true },
  ];
  await knex('system.lookup_definitions').insert(defs);

  function row(type, code, name_ro, name_en, order, extra = {}) {
    return { tenant_id: null, lookup_type: type, code, display_name: name_ro, display_name_en: name_en, sort_order: order, metadata: JSON.stringify(extra.metadata || {}), color: extra.color || null, icon: extra.icon || null, is_default: extra.is_default || false };
  }

  const values = [
    // stop_categories
    row('stop_categories', 'lipsa_material', 'Lipsa material', 'Lack of material', 1),
    row('stop_categories', 'defect_utilaj', 'Defect utilaj', 'Machine fault', 2),
    row('stop_categories', 'schimbare_produs', 'Schimbare produs', 'Product changeover', 3),
    row('stop_categories', 'reglaj', 'Reglaj', 'Setup', 4),
    row('stop_categories', 'lipsa_operator', 'Lipsa operator', 'Missing operator', 5),
    row('stop_categories', 'pauza', 'Pauza', 'Break', 6, { metadata: { is_planned: true } }),
    row('stop_categories', 'curatenie', 'Curatenie', 'Cleaning', 7, { metadata: { is_planned: true } }),
    row('stop_categories', 'lipsa_energie', 'Lipsa energie', 'Power outage', 8),
    row('stop_categories', 'asteptare_calitate', 'Asteptare calitate', 'Quality wait', 9),
    row('stop_categories', 'altul', 'Altul', 'Other', 99),
    // scrap_reasons
    row('scrap_reasons', 'uzura_scula', 'Uzura scula', 'Tool wear', 1),
    row('scrap_reasons', 'defect_suprafata', 'Defect suprafata', 'Surface defect', 2),
    row('scrap_reasons', 'cota_in_afara_tolerantei', 'Cota in afara tolerantei', 'Out of tolerance', 3),
    row('scrap_reasons', 'material_neconform', 'Material neconform', 'Non-conforming material', 4),
    row('scrap_reasons', 'rugozitate_neconforma', 'Rugozitate neconforma', 'Non-conforming roughness', 5),
    row('scrap_reasons', 'incomplet', 'Incomplet', 'Incomplete', 6),
    row('scrap_reasons', 'defect_vizual', 'Defect vizual', 'Visual defect', 7),
    row('scrap_reasons', 'eroare_operator', 'Eroare operator', 'Operator error', 8),
    row('scrap_reasons', 'altul', 'Altul', 'Other', 99),
    // machine_types
    row('machine_types', 'cnc_strung', 'CNC Strung', 'CNC Lathe', 1),
    row('machine_types', 'cnc_freza', 'CNC Freza', 'CNC Mill', 2),
    row('machine_types', 'cnc_router', 'CNC Router', 'CNC Router', 3),
    row('machine_types', 'injectie', 'Injectie', 'Injection moulding', 4),
    row('machine_types', 'presa', 'Presa', 'Press', 5),
    row('machine_types', 'asamblare', 'Asamblare', 'Assembly', 6),
    row('machine_types', 'sudura', 'Sudura', 'Welding', 7),
    row('machine_types', 'rectificare', 'Rectificare', 'Grinding', 8),
    row('machine_types', 'debitare', 'Debitare', 'Cutting', 9),
    row('machine_types', 'tratament_termic', 'Tratament termic', 'Heat treatment', 10),
    row('machine_types', 'vopsire', 'Vopsire', 'Painting', 11),
    row('machine_types', 'spalare', 'Spalare', 'Washing', 12),
    row('machine_types', 'banc_test', 'Banc test', 'Test bench', 13),
    row('machine_types', 'altul', 'Altul', 'Other', 99),
    // tool_types
    row('tool_types', 'matrita', 'Matrita', 'Mold', 1),
    row('tool_types', 'scula_cnc', 'Scula CNC', 'CNC tool', 2),
    row('tool_types', 'dispozitiv_fixare', 'Dispozitiv fixare', 'Fixture', 3),
    row('tool_types', 'calibru', 'Calibru', 'Gauge', 4),
    row('tool_types', 'electrode', 'Electrode', 'Electrode', 5),
    row('tool_types', 'cap_frezare', 'Cap frezare', 'Milling head', 6),
    row('tool_types', 'placute_amovibile', 'Placute amovibile', 'Inserts', 7),
    row('tool_types', 'burghiu', 'Burghiu', 'Drill', 8),
    row('tool_types', 'tarod', 'Tarod', 'Tap', 9),
    row('tool_types', 'alezor', 'Alezor', 'Reamer', 10),
    row('tool_types', 'freza', 'Freza', 'End mill', 11),
    row('tool_types', 'cutit_strung', 'Cutit strung', 'Lathe tool', 12),
    row('tool_types', 'altul', 'Altul', 'Other', 99),
    // item_categories
    row('item_categories', 'materie_prima', 'Materie prima', 'Raw material', 1),
    row('item_categories', 'semifabricat', 'Semifabricat', 'Semi-finished', 2),
    row('item_categories', 'produs_finit', 'Produs finit', 'Finished product', 3),
    row('item_categories', 'componenta_achizitionata', 'Componenta achizitionata', 'Purchased component', 4),
    row('item_categories', 'consumabil', 'Consumabil', 'Consumable', 5),
    row('item_categories', 'piesa_schimb', 'Piesa de schimb', 'Spare part', 6),
    row('item_categories', 'ambalaj', 'Ambalaj', 'Packaging', 7),
    row('item_categories', 'scula', 'Scula', 'Tool', 8),
    row('item_categories', 'altul', 'Altul', 'Other', 99),
    // units_of_measure
    row('units_of_measure', 'buc', 'Bucata', 'Piece', 1, { metadata: { symbol: 'buc', type: 'count' }, is_default: true }),
    row('units_of_measure', 'kg', 'Kilogram', 'Kilogram', 2, { metadata: { symbol: 'kg', type: 'weight' } }),
    row('units_of_measure', 'g', 'Gram', 'Gram', 3, { metadata: { symbol: 'g', type: 'weight' } }),
    row('units_of_measure', 'tona', 'Tona', 'Ton', 4, { metadata: { symbol: 't', type: 'weight' } }),
    row('units_of_measure', 'litru', 'Litru', 'Litre', 5, { metadata: { symbol: 'L', type: 'volume' } }),
    row('units_of_measure', 'ml', 'Mililitru', 'Millilitre', 6, { metadata: { symbol: 'ml', type: 'volume' } }),
    row('units_of_measure', 'm', 'Metru', 'Metre', 7, { metadata: { symbol: 'm', type: 'length' } }),
    row('units_of_measure', 'cm', 'Centimetru', 'Centimetre', 8, { metadata: { symbol: 'cm', type: 'length' } }),
    row('units_of_measure', 'mm', 'Milimetru', 'Millimetre', 9, { metadata: { symbol: 'mm', type: 'length' } }),
    row('units_of_measure', 'mp', 'Metru patrat', 'Square metre', 10, { metadata: { symbol: 'm²', type: 'area' } }),
    row('units_of_measure', 'mc', 'Metru cub', 'Cubic metre', 11, { metadata: { symbol: 'm³', type: 'volume' } }),
    row('units_of_measure', 'set', 'Set', 'Set', 12, { metadata: { symbol: 'set', type: 'count' } }),
    row('units_of_measure', 'pereche', 'Pereche', 'Pair', 13, { metadata: { symbol: 'pr', type: 'count' } }),
    row('units_of_measure', 'rola', 'Rola', 'Roll', 14, { metadata: { symbol: 'rl', type: 'count' } }),
    row('units_of_measure', 'palet', 'Palet', 'Pallet', 15, { metadata: { symbol: 'plt', type: 'count' } }),
    row('units_of_measure', 'cutie', 'Cutie', 'Box', 16, { metadata: { symbol: 'ctie', type: 'count' } }),
    row('units_of_measure', 'pachet', 'Pachet', 'Package', 17, { metadata: { symbol: 'pct', type: 'count' } }),
    // leave_types
    row('leave_types', 'concediu_odihna', 'Concediu odihna', 'Annual leave', 1, { metadata: { paid: true, requires_document: false, max_days_per_year: 21 } }),
    row('leave_types', 'concediu_medical', 'Concediu medical', 'Sick leave', 2, { metadata: { paid: true, requires_document: true, max_days_per_year: 90 } }),
    row('leave_types', 'formare_profesionala', 'Formare profesionala', 'Training', 3, { metadata: { paid: true, requires_document: false, max_days_per_year: 10 } }),
    row('leave_types', 'personal', 'Personal', 'Personal', 4, { metadata: { paid: false, requires_document: false, max_days_per_year: 3 } }),
    row('leave_types', 'fara_plata', 'Fara plata', 'Unpaid leave', 5, { metadata: { paid: false, requires_document: false, max_days_per_year: 30 } }),
    row('leave_types', 'recuperare', 'Recuperare', 'Compensatory', 6, { metadata: { paid: true, requires_document: false, max_days_per_year: 10 } }),
    row('leave_types', 'delegatie', 'Delegatie', 'Business trip', 7, { metadata: { paid: true, requires_document: true, max_days_per_year: 30 } }),
    row('leave_types', 'eveniment_familial', 'Eveniment familial', 'Family event', 8, { metadata: { paid: true, requires_document: true, max_days_per_year: 5 } }),
    row('leave_types', 'maternitate', 'Maternitate', 'Maternity', 9, { metadata: { paid: true, requires_document: true, max_days_per_year: 126 } }),
    row('leave_types', 'paternitate', 'Paternitate', 'Paternity', 10, { metadata: { paid: true, requires_document: true, max_days_per_year: 5 } }),
    row('leave_types', 'zi_compensatorie', 'Zi compensatorie', 'Compensatory day', 11, { metadata: { paid: true, requires_document: false, max_days_per_year: 20 } }),
    row('leave_types', 'altul', 'Altul', 'Other', 99, { metadata: { paid: false, requires_document: false, max_days_per_year: 0 } }),
    // intervention_types
    row('intervention_types', 'preventiva', 'Preventiva', 'Preventive', 1),
    row('intervention_types', 'corectiva', 'Corectiva', 'Corrective', 2),
    row('intervention_types', 'predictiva', 'Predictiva', 'Predictive', 3),
    row('intervention_types', 'calibrare', 'Calibrare', 'Calibration', 4),
    row('intervention_types', 'inspectie', 'Inspectie', 'Inspection', 5),
    row('intervention_types', 'upgrade', 'Upgrade', 'Upgrade', 6),
    row('intervention_types', 'instalare', 'Instalare', 'Installation', 7),
    row('intervention_types', 'mutare', 'Mutare', 'Relocation', 8),
    row('intervention_types', 'revopsire', 'Revopsire', 'Repainting', 9),
    row('intervention_types', 'dezafectare', 'Dezafectare', 'Decommission', 10),
    row('intervention_types', 'altul', 'Altul', 'Other', 99),
    // priority_levels
    row('priority_levels', 'scazut', 'Scazut', 'Low', 1, { color: '#6B7280', metadata: { severity_rank: 5, sla_hours: 120 } }),
    row('priority_levels', 'normal', 'Normal', 'Normal', 2, { color: '#3B82F6', metadata: { severity_rank: 4, sla_hours: 48 }, is_default: true }),
    row('priority_levels', 'ridicat', 'Ridicat', 'High', 3, { color: '#F59E0B', metadata: { severity_rank: 3, sla_hours: 24 } }),
    row('priority_levels', 'urgent', 'Urgent', 'Urgent', 4, { color: '#EF4444', metadata: { severity_rank: 2, sla_hours: 8 } }),
    row('priority_levels', 'critic', 'Critic', 'Critical', 5, { color: '#DC2626', metadata: { severity_rank: 1, sla_hours: 2 } }),
    // company_types
    row('company_types', 'client', 'Client', 'Client', 1, { is_default: true }),
    row('company_types', 'furnizor', 'Furnizor', 'Supplier', 2),
    row('company_types', 'subcontractor', 'Subcontractor', 'Subcontractor', 3),
    row('company_types', 'transportator', 'Transportator', 'Transporter', 4),
    row('company_types', 'firma_mentenanta', 'Firma mentenanta', 'Maintenance company', 5),
    row('company_types', 'laborator_testare', 'Laborator testare', 'Testing lab', 6),
    row('company_types', 'consultant', 'Consultant', 'Consultant', 7),
    row('company_types', 'prospect', 'Prospect', 'Prospect', 8),
    row('company_types', 'altul', 'Altul', 'Other', 99),
    // operation_types
    row('operation_types', 'debitare', 'Debitare', 'Cutting', 1),
    row('operation_types', 'strunjire', 'Strunjire', 'Turning', 2),
    row('operation_types', 'frezare', 'Frezare', 'Milling', 3),
    row('operation_types', 'gaurire', 'Gaurire', 'Drilling', 4),
    row('operation_types', 'rectificare', 'Rectificare', 'Grinding', 5),
    row('operation_types', 'sudura', 'Sudura', 'Welding', 6),
    row('operation_types', 'asamblare', 'Asamblare', 'Assembly', 7),
    row('operation_types', 'tratament_termic', 'Tratament termic', 'Heat treatment', 8),
    row('operation_types', 'vopsire', 'Vopsire', 'Painting', 9),
    row('operation_types', 'galvanizare', 'Galvanizare', 'Plating', 10),
    row('operation_types', 'spalare', 'Spalare', 'Washing', 11),
    row('operation_types', 'inspectie', 'Inspectie', 'Inspection', 12),
    row('operation_types', 'ambalare', 'Ambalare', 'Packaging', 13),
    row('operation_types', 'transport_intern', 'Transport intern', 'Internal transport', 14),
    row('operation_types', 'altul', 'Altul', 'Other', 99),
    // order_statuses
    row('order_statuses', 'draft', 'Ciorna', 'Draft', 1, { color: '#6B7280', metadata: { is_terminal: false, allowed_transitions: ['confirmed'] } }),
    row('order_statuses', 'confirmed', 'Confirmat', 'Confirmed', 2, { color: '#3B82F6', metadata: { is_terminal: false, allowed_transitions: ['materials_ready', 'in_production', 'cancelled'] } }),
    row('order_statuses', 'materials_ready', 'Materiale pregatite', 'Materials ready', 3, { color: '#8B5CF6', metadata: { is_terminal: false, allowed_transitions: ['in_production'] } }),
    row('order_statuses', 'in_production', 'In productie', 'In production', 4, { color: '#F59E0B', metadata: { is_terminal: false, allowed_transitions: ['quality_check', 'completed'] } }),
    row('order_statuses', 'quality_check', 'Control calitate', 'Quality check', 5, { color: '#06B6D4', metadata: { is_terminal: false, allowed_transitions: ['completed', 'in_production'] } }),
    row('order_statuses', 'completed', 'Finalizat', 'Completed', 6, { color: '#10B981', metadata: { is_terminal: false, allowed_transitions: ['shipped'] } }),
    row('order_statuses', 'shipped', 'Livrat', 'Shipped', 7, { color: '#6B7280', metadata: { is_terminal: true, allowed_transitions: [] } }),
    row('order_statuses', 'cancelled', 'Anulat', 'Cancelled', 8, { color: '#EF4444', metadata: { is_terminal: true, allowed_transitions: [] } }),
  ];

  await knex('system.lookup_values').insert(values);
  console.log(`[seed:lookups] Inserted ${values.length} lookup values across 12 types`);
}
